### ISSUE TITLE
Require local module silently fails

### ISSUE THREAD

**Issue by DimitryDushkin** [enb/enb-bemxjst#246]
```js
// make.js
requires: {
  routes: {
   commonJs: '../../server/routes/routes.js'  // path relative to index.bemhtml.js ?
  }
}
```

Silently fails to require local module.

I need this to have single module on backend and front-end.

**Comment by miripiruni** [comment]
@DimitryDushkin https://github.com/enb/enb-bemxjst#Подключение-сторонних-библиотек

> commonJS: 'path/to/lib-name'  // Путь к модулю CommonJS относительно собираемого файла

**Comment by DimitryDushkin** [comment]
Thanks) `commonJs -> commonJS`

**Comment by DimitryDushkin** [comment]
After fix I got next problem:
```js
// some.bemhtml.js
block('some').content()(function() {
 var routes = this.require('routes');
});
```

Produces error:
```
Error: Cannot find module '../../../server/routes/routes.js'
    at s (/Users/dndushkin/ydf/az-onco-front/front/desktop.bundles/index/index.bemhtml.js:6477:164)
    at s (/Users/dndushkin/ydf/az-onco-front/front/desktop.bundles/index/index.bemhtml.js:6477:130)
    at /Users/dndushkin/ydf/az-onco-front/front/desktop.bundles/index/index.bemhtml.js:7476:21
    at Object.<anonymous> (/Users/dndushkin/ydf/az-onco-front/front/desktop.bundles/index/index.bemhtml.js:7527:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
^C⏎
```

**Comment by miripiruni** [comment]
@DimitryDushkin it works, see example: https://github.yandex-team.ru/altay/altay-www/blob/master/.enb/make.js#L115

**Comment by tadatuta** [comment]
@DimitryDushkin 

```js
requires: {
    lib: { commonJS: path.resolve('./lib') }
}
```

**Comment by DimitryDushkin** [comment]
@miripiruni @tadatuta thx! It works!

 Please mention it in docs, that path must be absolute, not relative. Currently: 'Путь к модулю CommonJS **относительно** собираемого файла'.
